# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MesaNewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MesaNewsApp
  
  pod 'Alamofire'
  pod 'MaterialComponents'
  pod 'SteviaLayout'
  pod 'AlamofireImage', '~> 4.1'

end
